/**
 * Funnel v2 strings, used when the Directus quote page does not have the key
 * yet. Directus wins as soon as a key is translated there; this file is also
 * the source pushed to Directus, so the two never drift.
 * Keys are relative to `pages.<quote page>.`; `npm run quote-copy` writes the
 * missing ones to the charger quote page, which the battery funnel also reads.
 */
export const SHELL_COPY: Record<"fr" | "de", Record<string, string>> = {
  fr: {
    "quote.header.trust": "Données hébergées en Suisse",
    "quote.progress.stepOf": "Étape {n} sur {total}",
    "quote.progress.time.2min": "env. 2 min",
    "quote.progress.time.1min30": "env. 1 min 30",
    "quote.progress.time.1min": "env. 1 min",
    "quote.progress.time.under1": "moins d'1 min",
    "quote.progress.time.last": "dernière étape",
    "quote.prefill.label": "Déjà renseigné :",
    "quote.prefill.edit": "Modifier",
    "quote.missing": "Il manque une réponse à cette question.",
    "quote.leaveWarning": "Vos réponses sont enregistrées dans ce navigateur.",
    "quote.rail.title": "Ce que vous obtenez",
    "quote.rail.subsidy": "{locality} : subvention jusqu'à CHF {amount}",
    "quote.rail.subsidyAvailable": "{locality} : subvention communale disponible",
    "quote.rail.subsidyFallback": "Subvention de votre commune déduite du devis",
    "quote.rail.subsidySub": "L'installateur en tient compte dans son devis.",
    "quote.rail.installers": "{count} installateurs certifiés dans votre canton",
    "quote.rail.installersGeneric": "Des installateurs certifiés de votre région",
    "quote.rail.installersSub": "Le premier vous rappelle sous {first_contact} h.",
    "quote.rail.delay": "Devis sous {quote_delivery_timeline} jours",
    "quote.rail.delaySub": "Gratuit, sans engagement.",
    "quote.rail.answers": "Vos réponses",
    "quote.rail.edit": "Modifier",
    "quote.rail.next.title": "La suite",
    "quote.rail.next.1": "Un installateur vous appelle",
    "quote.rail.next.1sub": "Sous {first_contact} h, du lundi au vendredi.",
    "quote.rail.next.2": "Visite ou échange technique",
    "quote.rail.next.2sub": "Selon la complexité de l'installation.",
    "quote.rail.next.3": "Devis détaillé",
    "quote.rail.next.3sub": "Sous {quote_delivery_timeline} jours.",
    "quote.rail.rating": "{score} / 5 · {installations} installations",
    "steps.contact.title": "Où envoyer vos devis ?",
    "steps.contact.submit": "Recevoir mes devis",
    "steps.contact.fields.address.street": "Rue et numéro",
    "steps.contact.fields.address.toggleManual": "Saisir l'adresse manuellement",
    "steps.contact.fields.address.toggleGoogle": "Rechercher l'adresse",
    "steps.contact.fields.identity": "Vous",
    "steps.contact.fields.email.why": "pour recevoir les devis",
    "steps.contact.fields.phone.why": "l'installateur vous appelle sous {first_contact} h",
    "steps.contact.fields.comment.optional": "(facultatif)",
    "steps.contact.privacyNote": "Vos coordonnées ne sont transmises qu'aux installateurs retenus. Hébergement en Suisse.",
    "steps.housing.tenantExitAlt": "Demander un devis borne à la place",
    // Why we ask. Shared with the battery funnel (it reads this page as a
    // fallback), so housing texts must suit both products.
    "steps.housing.fields.housingStatus.why": "l'accord nécessaire en dépend",
    "steps.housing.fields.solarEquipment.why": "pour coordonner avec votre production",
    "steps.parking.fields.parkingSpotLocation.why": "pour estimer le passage du câble",
    "steps.charger.fields.parkingSpotCount.why": "pour dimensionner l'alimentation",
    "steps.charger.fields.deadline.why": "indicatif — aide l'installateur à planifier",
    "steps.vehicle.fields.vehicleStatus.why": "pour planifier la mise en service",
    // Optional questions after sending (flag quote-enrich).
    "steps.enrich.title": "Demande envoyée. Quelques précisions pour un devis plus juste ?",
    "steps.enrich.save": "Enregistrer",
    "steps.enrich.later": "Plus tard",
    "steps.enrich.saved": "Merci, c'est transmis avec votre demande.",
    "steps.enrich.fields.electricalBoardType.why": "pour vérifier la place au tableau",
    "steps.enrich.fields.electricalLineDistance.why": "pour dimensionner le câble",
    "steps.enrich.fields.electricalLineHoleCount.why": "pour estimer les percements",
    "steps.enrich.fields.ecpProvided.why": "pour savoir quelle borne chiffrer",
    "steps.enrich.fields.vehicleTripDistance.why": "pour adapter la puissance à vos trajets",
    "steps.enrich.fields.vehicleChargingHours.why": "pour choisir la puissance de charge",
  },
  de: {
    "quote.header.trust": "Daten in der Schweiz gespeichert",
    "quote.progress.stepOf": "Schritt {n} von {total}",
    "quote.progress.time.2min": "ca. 2 Min.",
    "quote.progress.time.1min30": "ca. 1½ Min.",
    "quote.progress.time.1min": "ca. 1 Min.",
    "quote.progress.time.under1": "weniger als 1 Min.",
    "quote.progress.time.last": "letzter Schritt",
    "quote.prefill.label": "Bereits angegeben:",
    "quote.prefill.edit": "Ändern",
    "quote.missing": "Diese Frage ist noch nicht beantwortet.",
    "quote.leaveWarning": "Ihre Antworten sind in diesem Browser gespeichert.",
    "quote.rail.title": "Das erhalten Sie",
    "quote.rail.subsidy": "{locality}: Förderbeitrag bis CHF {amount}",
    "quote.rail.subsidyAvailable": "{locality}: Förderprogramm der Gemeinde",
    "quote.rail.subsidyFallback": "Förderbeitrag Ihrer Gemeinde in der Offerte abgezogen",
    "quote.rail.subsidySub": "Der Installateur berücksichtigt ihn in der Offerte.",
    "quote.rail.installers": "{count} zertifizierte Installateure in Ihrem Kanton",
    "quote.rail.installersGeneric": "Zertifizierte Installateure aus Ihrer Region",
    "quote.rail.installersSub": "Der erste ruft Sie innert {first_contact} Std. zurück.",
    "quote.rail.delay": "Offerte innert {quote_delivery_timeline} Tagen",
    "quote.rail.delaySub": "Kostenlos und unverbindlich.",
    "quote.rail.answers": "Ihre Antworten",
    "quote.rail.edit": "Ändern",
    "quote.rail.next.title": "So geht es weiter",
    "quote.rail.next.1": "Ein Installateur ruft Sie an",
    "quote.rail.next.1sub": "Innert {first_contact} Std., Montag bis Freitag.",
    "quote.rail.next.2": "Besichtigung oder technisches Gespräch",
    "quote.rail.next.2sub": "Je nach Komplexität der Installation.",
    "quote.rail.next.3": "Detaillierte Offerte",
    "quote.rail.next.3sub": "Innert {quote_delivery_timeline} Tagen.",
    "quote.rail.rating": "{score} / 5 · {installations} Installationen",
    "steps.contact.title": "Wohin dürfen wir Ihre Offerten senden?",
    "steps.contact.submit": "Meine Offerten erhalten",
    "steps.contact.fields.address.street": "Strasse und Nr.",
    "steps.contact.fields.address.toggleManual": "Adresse manuell eingeben",
    "steps.contact.fields.address.toggleGoogle": "Adresse suchen",
    "steps.contact.fields.identity": "Sie",
    "steps.contact.fields.email.why": "für den Erhalt der Offerten",
    "steps.contact.fields.phone.why": "der Installateur ruft Sie innert {first_contact} Std. an",
    "steps.contact.fields.comment.optional": "(optional)",
    "steps.contact.privacyNote": "Ihre Angaben gehen nur an die ausgewählten Installateure. Hosting in der Schweiz.",
    "steps.housing.tenantExitAlt": "Stattdessen eine Offerte für eine Ladestation anfragen",
    "steps.housing.fields.housingStatus.why": "davon hängt die nötige Zustimmung ab",
    "steps.housing.fields.solarEquipment.why": "zur Abstimmung mit Ihrer Produktion",
    "steps.parking.fields.parkingSpotLocation.why": "für die Kabelführung",
    "steps.charger.fields.parkingSpotCount.why": "für die Auslegung der Zuleitung",
    "steps.charger.fields.deadline.why": "unverbindlich — hilft dem Installateur bei der Planung",
    "steps.vehicle.fields.vehicleStatus.why": "für die Planung der Inbetriebnahme",
    "steps.enrich.title": "Anfrage gesendet. Ein paar Angaben für eine genauere Offerte?",
    "steps.enrich.save": "Speichern",
    "steps.enrich.later": "Später",
    "steps.enrich.saved": "Danke, wir geben es mit Ihrer Anfrage weiter.",
    "steps.enrich.fields.electricalBoardType.why": "um den Platz im Verteiler zu prüfen",
    "steps.enrich.fields.electricalLineDistance.why": "für die Kabeldimensionierung",
    "steps.enrich.fields.electricalLineHoleCount.why": "für den Aufwand der Durchbrüche",
    "steps.enrich.fields.ecpProvided.why": "damit klar ist, welche Ladestation offeriert wird",
    "steps.enrich.fields.vehicleTripDistance.why": "um die Leistung an Ihre Fahrten anzupassen",
    "steps.enrich.fields.vehicleChargingHours.why": "für die Wahl der Ladeleistung",
  },
};
