export interface SwissPostalCode {
  postalCode: string;
  locality: string;
  canton: string;
}

export const swissPostalCodes: SwissPostalCode[] = [
  // Test entry
  { postalCode: "9999", locality: "TEST", canton: "TEST" },
  
  // Geneva (GE)
  { postalCode: "1200", locality: "Genève", canton: "GE" },
  { postalCode: "1201", locality: "Genève", canton: "GE" },
  { postalCode: "1202", locality: "Genève", canton: "GE" },
  { postalCode: "1203", locality: "Genève", canton: "GE" },
  { postalCode: "1204", locality: "Genève", canton: "GE" },
  { postalCode: "1205", locality: "Genève", canton: "GE" },
  { postalCode: "1206", locality: "Genève", canton: "GE" },
  { postalCode: "1207", locality: "Genève", canton: "GE" },
  { postalCode: "1208", locality: "Genève", canton: "GE" },
  { postalCode: "1209", locality: "Genève", canton: "GE" },
  { postalCode: "1211", locality: "Genève", canton: "GE" },
  { postalCode: "1212", locality: "Grand-Lancy", canton: "GE" },
  { postalCode: "1213", locality: "Petit-Lancy", canton: "GE" },
  { postalCode: "1214", locality: "Vernier", canton: "GE" },
  { postalCode: "1215", locality: "Genève", canton: "GE" },
  { postalCode: "1216", locality: "Cointrin", canton: "GE" },
  { postalCode: "1217", locality: "Meyrin", canton: "GE" },
  { postalCode: "1218", locality: "Le Grand-Saconnex", canton: "GE" },
  { postalCode: "1219", locality: "Le Lignon", canton: "GE" },
  { postalCode: "1220", locality: "Les Avanchets", canton: "GE" },
  { postalCode: "1222", locality: "Vésenaz", canton: "GE" },
  { postalCode: "1223", locality: "Cologny", canton: "GE" },
  { postalCode: "1224", locality: "Chêne-Bougeries", canton: "GE" },
  { postalCode: "1225", locality: "Chêne-Bourg", canton: "GE" },
  { postalCode: "1226", locality: "Thônex", canton: "GE" },
  { postalCode: "1227", locality: "Carouge", canton: "GE" },
  { postalCode: "1228", locality: "Plan-les-Ouates", canton: "GE" },
  { postalCode: "1231", locality: "Conches", canton: "GE" },
  { postalCode: "1232", locality: "Confignon", canton: "GE" },
  { postalCode: "1233", locality: "Bernex", canton: "GE" },
  { postalCode: "1234", locality: "Vessy", canton: "GE" },
  { postalCode: "1236", locality: "Cartigny", canton: "GE" },
  { postalCode: "1237", locality: "Avully", canton: "GE" },
  { postalCode: "1239", locality: "Collex", canton: "GE" },
  { postalCode: "1240", locality: "Genthod", canton: "GE" },
  { postalCode: "1241", locality: "Puplinge", canton: "GE" },
  { postalCode: "1242", locality: "Satigny", canton: "GE" },
  { postalCode: "1243", locality: "Presinge", canton: "GE" },
  { postalCode: "1244", locality: "Choulex", canton: "GE" },
  { postalCode: "1245", locality: "Collonge-Bellerive", canton: "GE" },
  { postalCode: "1246", locality: "Corsier", canton: "GE" },
  { postalCode: "1247", locality: "Anières", canton: "GE" },
  { postalCode: "1248", locality: "Hermance", canton: "GE" },
  { postalCode: "1251", locality: "Gy", canton: "GE" },
  { postalCode: "1252", locality: "Meinier", canton: "GE" },
  { postalCode: "1253", locality: "Vandoeuvres", canton: "GE" },
  { postalCode: "1254", locality: "Jussy", canton: "GE" },
  { postalCode: "1255", locality: "Veyrier", canton: "GE" },
  { postalCode: "1256", locality: "Troinex", canton: "GE" },
  { postalCode: "1257", locality: "La Croix-de-Rozon", canton: "GE" },
  { postalCode: "1258", locality: "Perly", canton: "GE" },
  { postalCode: "1283", locality: "Dardagny", canton: "GE" },
  { postalCode: "1284", locality: "Chancy", canton: "GE" },
  { postalCode: "1285", locality: "Athenaz", canton: "GE" },
  { postalCode: "1286", locality: "Soral", canton: "GE" },
  { postalCode: "1287", locality: "Laconnex", canton: "GE" },
  { postalCode: "1288", locality: "Aire-la-Ville", canton: "GE" },
  { postalCode: "1290", locality: "Versoix", canton: "GE" },
  { postalCode: "1291", locality: "Commugny", canton: "GE" },
  { postalCode: "1292", locality: "Chambésy", canton: "GE" },
  { postalCode: "1293", locality: "Bellevue", canton: "GE" },
  { postalCode: "1294", locality: "Genthod", canton: "GE" },
  { postalCode: "1295", locality: "Mies", canton: "GE" },
  { postalCode: "1296", locality: "Coppet", canton: "GE" },
  { postalCode: "1297", locality: "Founex", canton: "GE" },
  { postalCode: "1298", locality: "Céligny", canton: "GE" },

  // Vaud (VD) - principales localités
  { postalCode: "1000", locality: "Lausanne", canton: "VD" },
  { postalCode: "1001", locality: "Lausanne", canton: "VD" },
  { postalCode: "1002", locality: "Lausanne", canton: "VD" },
  { postalCode: "1003", locality: "Lausanne", canton: "VD" },
  { postalCode: "1004", locality: "Lausanne", canton: "VD" },
  { postalCode: "1005", locality: "Lausanne", canton: "VD" },
  { postalCode: "1006", locality: "Lausanne", canton: "VD" },
  { postalCode: "1007", locality: "Lausanne", canton: "VD" },
  { postalCode: "1008", locality: "Prilly", canton: "VD" },
  { postalCode: "1009", locality: "Pully", canton: "VD" },
  { postalCode: "1010", locality: "Lausanne", canton: "VD" },
  { postalCode: "1011", locality: "Lausanne", canton: "VD" },
  { postalCode: "1012", locality: "Lausanne", canton: "VD" },
  { postalCode: "1015", locality: "Lausanne", canton: "VD" },
  { postalCode: "1018", locality: "Lausanne", canton: "VD" },
  { postalCode: "1020", locality: "Renens", canton: "VD" },
  { postalCode: "1022", locality: "Chavannes-près-Renens", canton: "VD" },
  { postalCode: "1023", locality: "Crissier", canton: "VD" },
  { postalCode: "1024", locality: "Ecublens", canton: "VD" },
  { postalCode: "1025", locality: "St-Sulpice", canton: "VD" },
  { postalCode: "1026", locality: "Echandens", canton: "VD" },
  { postalCode: "1027", locality: "Lonay", canton: "VD" },
  { postalCode: "1028", locality: "Préverenges", canton: "VD" },
  { postalCode: "1029", locality: "Villars-Ste-Croix", canton: "VD" },
  { postalCode: "1030", locality: "Bussigny", canton: "VD" },
  { postalCode: "1032", locality: "Romanel-sur-Lausanne", canton: "VD" },
  { postalCode: "1033", locality: "Cheseaux-sur-Lausanne", canton: "VD" },
  { postalCode: "1034", locality: "Boussens", canton: "VD" },
  { postalCode: "1035", locality: "Bournens", canton: "VD" },
  { postalCode: "1036", locality: "Sullens", canton: "VD" },
  { postalCode: "1037", locality: "Etagnières", canton: "VD" },
  { postalCode: "1038", locality: "Bercher", canton: "VD" },
  { postalCode: "1039", locality: "Cheseaux-sur-Lausanne", canton: "VD" },
  { postalCode: "1040", locality: "Echallens", canton: "VD" },
  { postalCode: "1041", locality: "Poliez-le-Grand", canton: "VD" },
  { postalCode: "1042", locality: "Assens", canton: "VD" },
  { postalCode: "1043", locality: "Sugnens", canton: "VD" },
  { postalCode: "1044", locality: "Fey", canton: "VD" },
  { postalCode: "1045", locality: "Ogens", canton: "VD" },
  { postalCode: "1046", locality: "Rueyres", canton: "VD" },
  { postalCode: "1047", locality: "Oppens", canton: "VD" },
  { postalCode: "1052", locality: "Le Mont-sur-Lausanne", canton: "VD" },
  { postalCode: "1053", locality: "Cugy", canton: "VD" },
  { postalCode: "1054", locality: "Morrens", canton: "VD" },
  { postalCode: "1055", locality: "Froideville", canton: "VD" },
  { postalCode: "1058", locality: "Villars-Tiercelin", canton: "VD" },
  { postalCode: "1059", locality: "Peney-le-Jorat", canton: "VD" },
  { postalCode: "1061", locality: "Villars-Mendraz", canton: "VD" },
  { postalCode: "1062", locality: "Sottens", canton: "VD" },
  { postalCode: "1063", locality: "Chapelle-sur-Moudon", canton: "VD" },
  { postalCode: "1066", locality: "Epalinges", canton: "VD" },
  { postalCode: "1070", locality: "Puidoux", canton: "VD" },
  { postalCode: "1071", locality: "Chexbres", canton: "VD" },
  { postalCode: "1072", locality: "Forel", canton: "VD" },
  { postalCode: "1073", locality: "Savigny", canton: "VD" },
  { postalCode: "1077", locality: "Servion", canton: "VD" },
  { postalCode: "1078", locality: "Essertes", canton: "VD" },
  { postalCode: "1080", locality: "Les Cullayes", canton: "VD" },
  { postalCode: "1081", locality: "Montpreveyres", canton: "VD" },
  { postalCode: "1082", locality: "Corcelles-le-Jorat", canton: "VD" },
  { postalCode: "1083", locality: "Mézières", canton: "VD" },
  { postalCode: "1084", locality: "Carrouge", canton: "VD" },
  { postalCode: "1085", locality: "Vulliens", canton: "VD" },
  { postalCode: "1090", locality: "La Croix", canton: "VD" },
  { postalCode: "1091", locality: "Grandvaux", canton: "VD" },
  { postalCode: "1092", locality: "Belmont-sur-Lausanne", canton: "VD" },
  { postalCode: "1093", locality: "La Conversion", canton: "VD" },
  { postalCode: "1094", locality: "Paudex", canton: "VD" },
  { postalCode: "1095", locality: "Lutry", canton: "VD" },
  { postalCode: "1096", locality: "Cully", canton: "VD" },
  { postalCode: "1097", locality: "Riex", canton: "VD" },
  { postalCode: "1098", locality: "Epesses", canton: "VD" },
  { postalCode: "1110", locality: "Morges", canton: "VD" },
  { postalCode: "1112", locality: "Echichens", canton: "VD" },
  { postalCode: "1114", locality: "Colombier", canton: "VD" },
  { postalCode: "1115", locality: "Vullierens", canton: "VD" },
  { postalCode: "1116", locality: "Cottens", canton: "VD" },
  { postalCode: "1117", locality: "Grancy", canton: "VD" },
  { postalCode: "1121", locality: "Bremblens", canton: "VD" },
  { postalCode: "1122", locality: "Romanel-sur-Morges", canton: "VD" },
  { postalCode: "1123", locality: "Aclens", canton: "VD" },
  { postalCode: "1124", locality: "Gollion", canton: "VD" },
  { postalCode: "1125", locality: "Monnaz", canton: "VD" },
  { postalCode: "1126", locality: "Vaux-sur-Morges", canton: "VD" },
  { postalCode: "1127", locality: "Clarmont", canton: "VD" },
  { postalCode: "1128", locality: "Reverolle", canton: "VD" },
  { postalCode: "1131", locality: "Tolochenaz", canton: "VD" },
  { postalCode: "1132", locality: "Lully", canton: "VD" },
  { postalCode: "1134", locality: "Vufflens-le-Château", canton: "VD" },
  { postalCode: "1135", locality: "Denens", canton: "VD" },
  { postalCode: "1136", locality: "Bussy-Chardonney", canton: "VD" },
  { postalCode: "1141", locality: "Sévery", canton: "VD" },
  { postalCode: "1142", locality: "Pampigny", canton: "VD" },
  { postalCode: "1143", locality: "Apples", canton: "VD" },
  { postalCode: "1144", locality: "Ballens", canton: "VD" },
  { postalCode: "1145", locality: "Bière", canton: "VD" },
  { postalCode: "1146", locality: "Mollens", canton: "VD" },
  { postalCode: "1147", locality: "Montricher", canton: "VD" },
  { postalCode: "1148", locality: "L'Isle", canton: "VD" },
  { postalCode: "1162", locality: "St-Prex", canton: "VD" },
  { postalCode: "1163", locality: "Etoy", canton: "VD" },
  { postalCode: "1164", locality: "Buchillon", canton: "VD" },
  { postalCode: "1165", locality: "Allaman", canton: "VD" },
  { postalCode: "1166", locality: "Perroy", canton: "VD" },
  { postalCode: "1167", locality: "Lussy-sur-Morges", canton: "VD" },
  { postalCode: "1168", locality: "Villars-sous-Yens", canton: "VD" },
  { postalCode: "1169", locality: "Yens", canton: "VD" },
  { postalCode: "1170", locality: "Aubonne", canton: "VD" },
  { postalCode: "1172", locality: "Bougy-Villars", canton: "VD" },
  { postalCode: "1173", locality: "Féchy", canton: "VD" },
  { postalCode: "1174", locality: "Pizy", canton: "VD" },
  { postalCode: "1175", locality: "Lavigny", canton: "VD" },
  { postalCode: "1176", locality: "St-Livres", canton: "VD" },
  { postalCode: "1180", locality: "Rolle", canton: "VD" },
  { postalCode: "1182", locality: "Gilly", canton: "VD" },
  { postalCode: "1183", locality: "Bursins", canton: "VD" },
  { postalCode: "1184", locality: "Vinzel", canton: "VD" },
  { postalCode: "1185", locality: "Mont-sur-Rolle", canton: "VD" },
  { postalCode: "1186", locality: "Essertines-sur-Rolle", canton: "VD" },
  { postalCode: "1187", locality: "St-Oyens", canton: "VD" },
  { postalCode: "1188", locality: "Gimel", canton: "VD" },
  { postalCode: "1189", locality: "Saubraz", canton: "VD" },
  { postalCode: "1260", locality: "Nyon", canton: "VD" },
  { postalCode: "1261", locality: "Le Vaud", canton: "VD" },
  { postalCode: "1262", locality: "Eysins", canton: "VD" },
  { postalCode: "1263", locality: "Crassier", canton: "VD" },
  { postalCode: "1264", locality: "St-Cergue", canton: "VD" },
  { postalCode: "1265", locality: "La Cure", canton: "VD" },
  { postalCode: "1266", locality: "Duillier", canton: "VD" },
  { postalCode: "1267", locality: "Vich", canton: "VD" },
  { postalCode: "1268", locality: "Begnins", canton: "VD" },
  { postalCode: "1269", locality: "Bassins", canton: "VD" },
  { postalCode: "1270", locality: "Trélex", canton: "VD" },
  { postalCode: "1271", locality: "Givrins", canton: "VD" },
  { postalCode: "1272", locality: "Genolier", canton: "VD" },
  { postalCode: "1273", locality: "Arzier-Le Muids", canton: "VD" },
  { postalCode: "1274", locality: "Grens", canton: "VD" },
  { postalCode: "1275", locality: "Chéserex", canton: "VD" },
  { postalCode: "1276", locality: "Gingins", canton: "VD" },
  { postalCode: "1277", locality: "Borex", canton: "VD" },
  { postalCode: "1278", locality: "La Rippe", canton: "VD" },
  { postalCode: "1279", locality: "Chavannes-de-Bogis", canton: "VD" },
  { postalCode: "1281", locality: "Russin", canton: "GE" },
  { postalCode: "1299", locality: "Crans-près-Céligny", canton: "VD" },
  { postalCode: "1302", locality: "Vufflens-la-Ville", canton: "VD" },
  { postalCode: "1303", locality: "Penthaz", canton: "VD" },
  { postalCode: "1304", locality: "Cossonay", canton: "VD" },
  { postalCode: "1305", locality: "Penthalaz", canton: "VD" },
  { postalCode: "1306", locality: "Daillens", canton: "VD" },
  { postalCode: "1307", locality: "Lussery-Villars", canton: "VD" },
  { postalCode: "1308", locality: "La Chaux", canton: "VD" },
  { postalCode: "1309", locality: "Eclépens", canton: "VD" },
  { postalCode: "1310", locality: "Daillens", canton: "VD" },
  { postalCode: "1312", locality: "Eclépens", canton: "VD" },
  { postalCode: "1313", locality: "Ferreyres", canton: "VD" },
  { postalCode: "1315", locality: "La Sarraz", canton: "VD" },
  { postalCode: "1316", locality: "Chevilly", canton: "VD" },
  { postalCode: "1317", locality: "Orny", canton: "VD" },
  { postalCode: "1318", locality: "Pompaples", canton: "VD" },
  { postalCode: "1321", locality: "Arnex-sur-Orbe", canton: "VD" },
  { postalCode: "1322", locality: "Croy", canton: "VD" },
  { postalCode: "1323", locality: "Romainmôtier", canton: "VD" },
  { postalCode: "1324", locality: "Premier", canton: "VD" },
  { postalCode: "1325", locality: "Vaulion", canton: "VD" },
  { postalCode: "1326", locality: "Juriens", canton: "VD" },
  { postalCode: "1329", locality: "Bretonnières", canton: "VD" },
  { postalCode: "1337", locality: "Vallorbe", canton: "VD" },
  { postalCode: "1338", locality: "Ballaigues", canton: "VD" },
  { postalCode: "1341", locality: "L'Orient", canton: "VD" },
  { postalCode: "1342", locality: "Le Pont", canton: "VD" },
  { postalCode: "1343", locality: "Les Charbonnières", canton: "VD" },
  { postalCode: "1344", locality: "L'Abbaye", canton: "VD" },
  { postalCode: "1345", locality: "Le Lieu", canton: "VD" },
  { postalCode: "1346", locality: "Les Bioux", canton: "VD" },
  { postalCode: "1347", locality: "Le Sentier", canton: "VD" },
  { postalCode: "1348", locality: "Le Brassus", canton: "VD" },
  { postalCode: "1350", locality: "Orbe", canton: "VD" },
  { postalCode: "1352", locality: "Agiez", canton: "VD" },
  { postalCode: "1353", locality: "Bofflens", canton: "VD" },
  { postalCode: "1354", locality: "Montcherand", canton: "VD" },
  { postalCode: "1355", locality: "L'Abergement", canton: "VD" },
  { postalCode: "1356", locality: "La Russille", canton: "VD" },
  { postalCode: "1357", locality: "Lignerolle", canton: "VD" },
  { postalCode: "1358", locality: "Valeyres-sous-Rances", canton: "VD" },
  { postalCode: "1400", locality: "Yverdon-les-Bains", canton: "VD" },
  { postalCode: "1401", locality: "Yverdon-les-Bains", canton: "VD" },
  { postalCode: "1404", locality: "Cuarny", canton: "VD" },
  { postalCode: "1405", locality: "Pomy", canton: "VD" },
  { postalCode: "1406", locality: "Cronay", canton: "VD" },
  { postalCode: "1407", locality: "Donneloye", canton: "VD" },
  { postalCode: "1408", locality: "Prahins", canton: "VD" },
  { postalCode: "1409", locality: "Chanéaz", canton: "VD" },
  { postalCode: "1410", locality: "Thierrens", canton: "VD" },
  { postalCode: "1411", locality: "Ogens", canton: "VD" },
  { postalCode: "1412", locality: "Valeyres-sous-Ursins", canton: "VD" },
  { postalCode: "1413", locality: "Orzens", canton: "VD" },
  { postalCode: "1415", locality: "Démoret", canton: "VD" },
  { postalCode: "1416", locality: "Pailly", canton: "VD" },
  { postalCode: "1417", locality: "Essertines-sur-Yverdon", canton: "VD" },
  { postalCode: "1418", locality: "Vuarrens", canton: "VD" },
  { postalCode: "1420", locality: "Fiez", canton: "VD" },
  { postalCode: "1421", locality: "Fontaines-sur-Grandson", canton: "VD" },
  { postalCode: "1422", locality: "Grandson", canton: "VD" },
  { postalCode: "1423", locality: "Villars-Burquin", canton: "VD" },
  { postalCode: "1424", locality: "Champagne", canton: "VD" },
  { postalCode: "1425", locality: "Onnens", canton: "VD" },
  { postalCode: "1426", locality: "Concise", canton: "VD" },
  { postalCode: "1427", locality: "Bonvillars", canton: "VD" },
  { postalCode: "1428", locality: "Mutrux", canton: "VD" },
  { postalCode: "1429", locality: "Giez", canton: "VD" },
  { postalCode: "1430", locality: "Orges", canton: "VD" },
  { postalCode: "1431", locality: "Vugelles-La Mothe", canton: "VD" },
  { postalCode: "1432", locality: "Belmont-sur-Yverdon", canton: "VD" },
  { postalCode: "1433", locality: "Suchy", canton: "VD" },
  { postalCode: "1434", locality: "Ependes", canton: "VD" },
  { postalCode: "1435", locality: "Essert-Pittet", canton: "VD" },
  { postalCode: "1436", locality: "Treycovagnes", canton: "VD" },
  { postalCode: "1437", locality: "Suscévaz", canton: "VD" },
  { postalCode: "1438", locality: "Mathod", canton: "VD" },
  { postalCode: "1439", locality: "Rances", canton: "VD" },
  { postalCode: "1441", locality: "Valeyres-sous-Montagny", canton: "VD" },
  { postalCode: "1442", locality: "Montagny-près-Yverdon", canton: "VD" },
  { postalCode: "1443", locality: "Champvent", canton: "VD" },
  { postalCode: "1444", locality: "Eysins", canton: "VD" },
  { postalCode: "1445", locality: "Vuiteboeuf", canton: "VD" },
  { postalCode: "1446", locality: "Baulmes", canton: "VD" },
  { postalCode: "1450", locality: "Ste-Croix", canton: "VD" },
  { postalCode: "1451", locality: "Ste-Croix", canton: "VD" },
  { postalCode: "1452", locality: "Les Rasses", canton: "VD" },
  { postalCode: "1453", locality: "Bullet", canton: "VD" },
  { postalCode: "1454", locality: "L'Auberson", canton: "VD" },
  { postalCode: "1462", locality: "Yvonand", canton: "VD" },
  { postalCode: "1463", locality: "Rovray", canton: "VD" },
  { postalCode: "1464", locality: "Chêne-Pâquier", canton: "VD" },
  { postalCode: "1468", locality: "Cheyres", canton: "FR" },
  { postalCode: "1470", locality: "Estavayer-le-Lac", canton: "FR" },
  { postalCode: "1473", locality: "Font", canton: "FR" },
  { postalCode: "1474", locality: "Châbles", canton: "FR" },
  { postalCode: "1475", locality: "Autavaux", canton: "FR" },
  { postalCode: "1476", locality: "Hautomne", canton: "VD" },
  { postalCode: "1482", locality: "Cugy", canton: "FR" },
  { postalCode: "1483", locality: "Montet", canton: "FR" },
  { postalCode: "1484", locality: "Aumont", canton: "FR" },
  { postalCode: "1485", locality: "Nuvilly", canton: "FR" },
  { postalCode: "1509", locality: "Vucherens", canton: "VD" },
  { postalCode: "1510", locality: "Moudon", canton: "VD" },
  { postalCode: "1512", locality: "Chavannes-sur-Moudon", canton: "VD" },
  { postalCode: "1513", locality: "Hermenches", canton: "VD" },
  { postalCode: "1514", locality: "Bussy-sur-Moudon", canton: "VD" },
  { postalCode: "1515", locality: "Neyruz-sur-Moudon", canton: "VD" },
  { postalCode: "1521", locality: "Curtilles", canton: "VD" },
  { postalCode: "1522", locality: "Lucens", canton: "VD" },
  { postalCode: "1523", locality: "Granges-près-Marnand", canton: "VD" },
  { postalCode: "1524", locality: "Marnand", canton: "VD" },
  { postalCode: "1525", locality: "Seigneux", canton: "VD" },
  { postalCode: "1526", locality: "Forel-sur-Lucens", canton: "VD" },
  { postalCode: "1527", locality: "Villeneuve", canton: "FR" },
  { postalCode: "1528", locality: "Praratoud", canton: "FR" },
  { postalCode: "1529", locality: "Cheiry", canton: "FR" },
  { postalCode: "1530", locality: "Payerne", canton: "VD" },
  { postalCode: "1532", locality: "Fétigny", canton: "FR" },
  { postalCode: "1533", locality: "Ménières", canton: "FR" },
  { postalCode: "1534", locality: "Sassel", canton: "VD" },
  { postalCode: "1535", locality: "Combremont-le-Grand", canton: "VD" },
  { postalCode: "1536", locality: "Combremont-le-Petit", canton: "VD" },
  { postalCode: "1537", locality: "Champtauroz", canton: "VD" },
  { postalCode: "1538", locality: "Treytorrens", canton: "VD" },
  { postalCode: "1541", locality: "Bussy-sur-Moudon", canton: "FR" },
  { postalCode: "1542", locality: "Rueyres-les-Prés", canton: "FR" },
  { postalCode: "1543", locality: "Grandcour", canton: "VD" },
  { postalCode: "1544", locality: "Gletterens", canton: "FR" },
  { postalCode: "1545", locality: "Chevroux", canton: "VD" },
  { postalCode: "1553", locality: "Châtonnaye", canton: "FR" },
  { postalCode: "1554", locality: "Sédeilles", canton: "VD" },
  { postalCode: "1555", locality: "Villarzel", canton: "VD" },
  { postalCode: "1562", locality: "Corcelles-près-Payerne", canton: "VD" },
  { postalCode: "1563", locality: "Dompierre", canton: "FR" },
  { postalCode: "1564", locality: "Domdidier", canton: "FR" },
  { postalCode: "1565", locality: "Vallon", canton: "FR" },
  { postalCode: "1566", locality: "St-Aubin", canton: "FR" },
  { postalCode: "1567", locality: "Delley", canton: "FR" },
  { postalCode: "1568", locality: "Portalban", canton: "FR" },
  { postalCode: "1580", locality: "Avenches", canton: "VD" },
  { postalCode: "1582", locality: "Donatyre", canton: "VD" },
  { postalCode: "1583", locality: "Villarepos", canton: "FR" },
  { postalCode: "1584", locality: "Villars-le-Grand", canton: "VD" },
  { postalCode: "1585", locality: "Salavaux", canton: "VD" },
  { postalCode: "1586", locality: "Vallamand", canton: "VD" },
  { postalCode: "1587", locality: "Montmagny", canton: "VD" },
  { postalCode: "1588", locality: "Cudrefin", canton: "VD" },
  { postalCode: "1589", locality: "Chabrey", canton: "VD" },
  { postalCode: "1595", locality: "Faoug", canton: "VD" },
  { postalCode: "1607", locality: "Palézieux", canton: "VD" },
  { postalCode: "1608", locality: "Oron-le-Châtel", canton: "VD" },
  { postalCode: "1609", locality: "St-Martin", canton: "VD" },
  { postalCode: "1610", locality: "Oron-la-Ville", canton: "VD" },
  { postalCode: "1611", locality: "Le Crêt-près-Semsales", canton: "FR" },
  { postalCode: "1612", locality: "Ecoteaux", canton: "VD" },
  { postalCode: "1613", locality: "Maracon", canton: "VD" },
  { postalCode: "1614", locality: "Granges", canton: "VD" },
  { postalCode: "1615", locality: "Bossonnens", canton: "FR" },
  { postalCode: "1616", locality: "Attalens", canton: "FR" },
  { postalCode: "1617", locality: "Remaufens", canton: "FR" },
  { postalCode: "1618", locality: "Châtel-St-Denis", canton: "FR" },
  { postalCode: "1619", locality: "Les Paccots", canton: "FR" },
  { postalCode: "1623", locality: "Semsales", canton: "FR" },
  { postalCode: "1624", locality: "La Verrerie", canton: "FR" },
  { postalCode: "1625", locality: "Sâles", canton: "FR" },
  { postalCode: "1626", locality: "Romanens", canton: "FR" },
  { postalCode: "1627", locality: "Vaulruz", canton: "FR" },
  { postalCode: "1628", locality: "Vuadens", canton: "FR" },
  { postalCode: "1630", locality: "Bulle", canton: "FR" },
  { postalCode: "1631", locality: "Bulle", canton: "FR" },
  { postalCode: "1632", locality: "Riaz", canton: "FR" },
  { postalCode: "1633", locality: "Vuippens", canton: "FR" },
  { postalCode: "1634", locality: "La Roche", canton: "FR" },
  { postalCode: "1635", locality: "La Tour-de-Trême", canton: "FR" },
  { postalCode: "1636", locality: "Broc", canton: "FR" },
  { postalCode: "1637", locality: "Charmey", canton: "FR" },
  { postalCode: "1638", locality: "Morlon", canton: "FR" },
  { postalCode: "1642", locality: "Sorens", canton: "FR" },
  { postalCode: "1643", locality: "Gumefens", canton: "FR" },
  { postalCode: "1644", locality: "Avry-devant-Pont", canton: "FR" },
  { postalCode: "1645", locality: "Le Bry", canton: "FR" },
  { postalCode: "1646", locality: "Echarlens", canton: "FR" },
  { postalCode: "1647", locality: "Corbières", canton: "FR" },
  { postalCode: "1648", locality: "Hauteville", canton: "FR" },
  { postalCode: "1649", locality: "Pont-la-Ville", canton: "FR" },
  { postalCode: "1651", locality: "Villarvolard", canton: "FR" },
  { postalCode: "1652", locality: "Botterens", canton: "FR" },
  { postalCode: "1653", locality: "Crésuz", canton: "FR" },
  { postalCode: "1654", locality: "Cerniat", canton: "FR" },
  { postalCode: "1656", locality: "Jaun", canton: "FR" },
  { postalCode: "1657", locality: "Abländschen", canton: "FR" },
  { postalCode: "1658", locality: "Rossinière", canton: "VD" },
  { postalCode: "1659", locality: "Rougemont", canton: "VD" },
  { postalCode: "1660", locality: "La Lécherette", canton: "VD" },
  { postalCode: "1661", locality: "Le Pâquier-Montbarry", canton: "FR" },
  { postalCode: "1663", locality: "Epagny", canton: "FR" },
  { postalCode: "1663", locality: "Gruyères", canton: "FR" },
  { postalCode: "1663", locality: "Pringy", canton: "FR" },
  { postalCode: "1664", locality: "Chapelle", canton: "FR" },
  { postalCode: "1665", locality: "Estavannens", canton: "FR" },
  { postalCode: "1666", locality: "Villars-sous-Mont", canton: "FR" },
  { postalCode: "1667", locality: "Enney", canton: "FR" },
  { postalCode: "1699", locality: "Bouloz", canton: "FR" },
  { postalCode: "1699", locality: "Porsel", canton: "FR" },
  { postalCode: "1700", locality: "Fribourg", canton: "FR" },
  { postalCode: "1701", locality: "Fribourg", canton: "FR" },
  { postalCode: "1702", locality: "Fribourg", canton: "FR" },
  { postalCode: "1800", locality: "Vevey", canton: "VD" },
  { postalCode: "1801", locality: "Le Mont-Pèlerin", canton: "VD" },
  { postalCode: "1802", locality: "Corseaux", canton: "VD" },
  { postalCode: "1803", locality: "Chardonne", canton: "VD" },
  { postalCode: "1804", locality: "Corsier-sur-Vevey", canton: "VD" },
  { postalCode: "1805", locality: "Jongny", canton: "VD" },
  { postalCode: "1806", locality: "St-Légier-La Chiésaz", canton: "VD" },
  { postalCode: "1807", locality: "Blonay", canton: "VD" },
  { postalCode: "1808", locality: "Les Monts-de-Corsier", canton: "VD" },
  { postalCode: "1809", locality: "Fenil-sur-Corsier", canton: "VD" },
  { postalCode: "1810", locality: "Chardonne", canton: "VD" },
  { postalCode: "1814", locality: "La Tour-de-Peilz", canton: "VD" },
  { postalCode: "1815", locality: "Clarens", canton: "VD" },
  { postalCode: "1816", locality: "Chailly-Montreux", canton: "VD" },
  { postalCode: "1817", locality: "Brent", canton: "VD" },
  { postalCode: "1818", locality: "Montreux", canton: "VD" },
  { postalCode: "1820", locality: "Montreux", canton: "VD" },
  { postalCode: "1822", locality: "Chernex", canton: "VD" },
  { postalCode: "1823", locality: "Glion", canton: "VD" },
  { postalCode: "1824", locality: "Caux", canton: "VD" },
  { postalCode: "1832", locality: "Chamby", canton: "VD" },
  { postalCode: "1833", locality: "Les Avants", canton: "VD" },
  { postalCode: "1844", locality: "Villeneuve", canton: "VD" },
  { postalCode: "1845", locality: "Noville", canton: "VD" },
  { postalCode: "1846", locality: "Chessel", canton: "VD" },
  { postalCode: "1847", locality: "Rennaz", canton: "VD" },
  { postalCode: "1852", locality: "Roche", canton: "VD" },
  { postalCode: "1853", locality: "Yvorne", canton: "VD" },
  { postalCode: "1854", locality: "Leysin", canton: "VD" },
  { postalCode: "1856", locality: "Corbeyrier", canton: "VD" },
  { postalCode: "1860", locality: "Aigle", canton: "VD" },
  { postalCode: "1862", locality: "Les Mosses", canton: "VD" },
  { postalCode: "1863", locality: "Le Sépey", canton: "VD" },
  { postalCode: "1864", locality: "Vers-l'Eglise", canton: "VD" },
  { postalCode: "1865", locality: "Les Diablerets", canton: "VD" },
  { postalCode: "1866", locality: "La Forclaz", canton: "VD" },
  { postalCode: "1867", locality: "Ollon", canton: "VD" },
  { postalCode: "1868", locality: "Collombey", canton: "VS" },
  { postalCode: "1870", locality: "Monthey", canton: "VS" },
  { postalCode: "1871", locality: "Choëx", canton: "VS" },
  { postalCode: "1872", locality: "Troistorrents", canton: "VS" },
  { postalCode: "1873", locality: "Val-d'Illiez", canton: "VS" },
  { postalCode: "1874", locality: "Champéry", canton: "VS" },
  { postalCode: "1875", locality: "Morgins", canton: "VS" },
  { postalCode: "1890", locality: "St-Maurice", canton: "VS" },
  { postalCode: "1891", locality: "Vérossaz", canton: "VS" },
  { postalCode: "1892", locality: "Lavey-Village", canton: "VD" },
  { postalCode: "1893", locality: "Muraz", canton: "VS" },
  { postalCode: "1895", locality: "Vionnaz", canton: "VS" },
  { postalCode: "1896", locality: "Vouvry", canton: "VS" },
  { postalCode: "1897", locality: "Les Evouettes", canton: "VS" },
  { postalCode: "1898", locality: "St-Gingolph", canton: "VS" },
  { postalCode: "1899", locality: "Torgon", canton: "VS" },

  // Fribourg (FR) - principales localités
  { postalCode: "1700", locality: "Fribourg", canton: "FR" },
  { postalCode: "1701", locality: "Fribourg", canton: "FR" },
  { postalCode: "1702", locality: "Fribourg", canton: "FR" },
  { postalCode: "1705", locality: "Fribourg", canton: "FR" },
  { postalCode: "1707", locality: "Fribourg", canton: "FR" },
  { postalCode: "1708", locality: "Fribourg", canton: "FR" },
  { postalCode: "1709", locality: "Fribourg", canton: "FR" },
  { postalCode: "1712", locality: "Tafers", canton: "FR" },
  { postalCode: "1713", locality: "St. Antoni", canton: "FR" },
  { postalCode: "1714", locality: "Heitenried", canton: "FR" },
  { postalCode: "1715", locality: "Alterswil", canton: "FR" },
  { postalCode: "1716", locality: "Plaffeien", canton: "FR" },
  { postalCode: "1717", locality: "St. Ursen", canton: "FR" },
  { postalCode: "1718", locality: "Rechthalten", canton: "FR" },
  { postalCode: "1719", locality: "Zumholz", canton: "FR" },
  { postalCode: "1720", locality: "Corminboeuf", canton: "FR" },
  { postalCode: "1721", locality: "Courtion", canton: "FR" },
  { postalCode: "1722", locality: "Bourguillon", canton: "FR" },
  { postalCode: "1723", locality: "Marly", canton: "FR" },
  { postalCode: "1724", locality: "Bonnefontaine", canton: "FR" },
  { postalCode: "1725", locality: "Posieux", canton: "FR" },
  { postalCode: "1726", locality: "Farvagny", canton: "FR" },
  { postalCode: "1727", locality: "Corpataux", canton: "FR" },
  { postalCode: "1728", locality: "Rossens", canton: "FR" },
  { postalCode: "1730", locality: "Ecuvillens", canton: "FR" },
  { postalCode: "1731", locality: "Ependes", canton: "FR" },
  { postalCode: "1732", locality: "Arconciel", canton: "FR" },
  { postalCode: "1733", locality: "Treyvaux", canton: "FR" },
  { postalCode: "1734", locality: "Tentlingen", canton: "FR" },
  { postalCode: "1735", locality: "Giffers", canton: "FR" },
  { postalCode: "1736", locality: "St. Silvester", canton: "FR" },
  { postalCode: "1737", locality: "Plasselb", canton: "FR" },
  { postalCode: "1740", locality: "Neyruz", canton: "FR" },
  { postalCode: "1741", locality: "Cottens", canton: "FR" },
  { postalCode: "1742", locality: "Autigny", canton: "FR" },
  { postalCode: "1744", locality: "Chénens", canton: "FR" },
  { postalCode: "1745", locality: "Lentigny", canton: "FR" },
  { postalCode: "1746", locality: "Prez-vers-Noréaz", canton: "FR" },
  { postalCode: "1747", locality: "Corserey", canton: "FR" },
  { postalCode: "1748", locality: "Torny-le-Grand", canton: "FR" },
  { postalCode: "1749", locality: "Middes", canton: "FR" },
  { postalCode: "1752", locality: "Villars-sur-Glâne", canton: "FR" },
  { postalCode: "1753", locality: "Matran", canton: "FR" },
  { postalCode: "1754", locality: "Avry-sur-Matran", canton: "FR" },
  { postalCode: "1754", locality: "Rosé", canton: "FR" },
  { postalCode: "1756", locality: "Onnens", canton: "FR" },
  { postalCode: "1757", locality: "Noréaz", canton: "FR" },
  { postalCode: "1762", locality: "Givisiez", canton: "FR" },
  { postalCode: "1763", locality: "Granges-Paccot", canton: "FR" },
  { postalCode: "1772", locality: "Grolley", canton: "FR" },
  { postalCode: "1773", locality: "Léchelles", canton: "FR" },
  { postalCode: "1774", locality: "Montagny-les-Monts", canton: "FR" },
  { postalCode: "1775", locality: "Grandsivaz", canton: "FR" },
  { postalCode: "1776", locality: "Montagny-la-Ville", canton: "FR" },
  { postalCode: "1782", locality: "Belfaux", canton: "FR" },
  { postalCode: "1783", locality: "Pensier", canton: "FR" },
  { postalCode: "1784", locality: "Courtepin", canton: "FR" },
  { postalCode: "1785", locality: "Cressier", canton: "FR" },
  { postalCode: "1786", locality: "Sugiez", canton: "FR" },
  { postalCode: "1787", locality: "Môtier", canton: "FR" },
  { postalCode: "1788", locality: "Praz", canton: "FR" },
  { postalCode: "1789", locality: "Lugnorre", canton: "FR" },
  { postalCode: "1791", locality: "Courtaman", canton: "FR" },
  { postalCode: "1792", locality: "Cordast", canton: "FR" },
  { postalCode: "1793", locality: "Jeuss", canton: "FR" },
  { postalCode: "1794", locality: "Salvenach", canton: "FR" },
  { postalCode: "1795", locality: "Courlevon", canton: "FR" },
  { postalCode: "1796", locality: "Courgevaux", canton: "FR" },
  { postalCode: "1797", locality: "Münchenwiler", canton: "FR" },

  // Valais (VS) - principales localités Romandie
  { postalCode: "1870", locality: "Monthey", canton: "VS" },
  { postalCode: "1871", locality: "Choëx", canton: "VS" },
  { postalCode: "1872", locality: "Troistorrents", canton: "VS" },
  { postalCode: "1873", locality: "Val-d'Illiez", canton: "VS" },
  { postalCode: "1874", locality: "Champéry", canton: "VS" },
  { postalCode: "1875", locality: "Morgins", canton: "VS" },
  { postalCode: "1890", locality: "St-Maurice", canton: "VS" },
  { postalCode: "1891", locality: "Vérossaz", canton: "VS" },
  { postalCode: "1893", locality: "Muraz", canton: "VS" },
  { postalCode: "1895", locality: "Vionnaz", canton: "VS" },
  { postalCode: "1896", locality: "Vouvry", canton: "VS" },
  { postalCode: "1897", locality: "Les Evouettes", canton: "VS" },
  { postalCode: "1898", locality: "St-Gingolph", canton: "VS" },
  { postalCode: "1899", locality: "Torgon", canton: "VS" },
  { postalCode: "1902", locality: "Evionnaz", canton: "VS" },
  { postalCode: "1903", locality: "Collonges", canton: "VS" },
  { postalCode: "1904", locality: "Vernayaz", canton: "VS" },
  { postalCode: "1905", locality: "Dorénaz", canton: "VS" },
  { postalCode: "1906", locality: "Charrat", canton: "VS" },
  { postalCode: "1907", locality: "Saxon", canton: "VS" },
  { postalCode: "1908", locality: "Riddes", canton: "VS" },
  { postalCode: "1911", locality: "Ovronnaz", canton: "VS" },
  { postalCode: "1912", locality: "Leytron", canton: "VS" },
  { postalCode: "1913", locality: "Saillon", canton: "VS" },
  { postalCode: "1914", locality: "Isérables", canton: "VS" },
  { postalCode: "1918", locality: "La Tzoumaz", canton: "VS" },
  { postalCode: "1920", locality: "Martigny", canton: "VS" },
  { postalCode: "1921", locality: "Martigny-Croix", canton: "VS" },
  { postalCode: "1922", locality: "Salvan", canton: "VS" },
  { postalCode: "1923", locality: "Les Marécottes", canton: "VS" },
  { postalCode: "1925", locality: "Finhaut", canton: "VS" },
  { postalCode: "1926", locality: "Fully", canton: "VS" },
  { postalCode: "1927", locality: "Chemin", canton: "VS" },
  { postalCode: "1928", locality: "Ravoire", canton: "VS" },
  { postalCode: "1929", locality: "Trient", canton: "VS" },
  { postalCode: "1932", locality: "Les Valettes", canton: "VS" },
  { postalCode: "1933", locality: "Sembrancher", canton: "VS" },
  { postalCode: "1934", locality: "Le Châble", canton: "VS" },
  { postalCode: "1936", locality: "Verbier", canton: "VS" },
  { postalCode: "1937", locality: "Orsières", canton: "VS" },
  { postalCode: "1938", locality: "Champex-Lac", canton: "VS" },
  { postalCode: "1941", locality: "Vollèges", canton: "VS" },
  { postalCode: "1942", locality: "Levron", canton: "VS" },
  { postalCode: "1943", locality: "Praz-de-Fort", canton: "VS" },
  { postalCode: "1944", locality: "La Fouly", canton: "VS" },
  { postalCode: "1945", locality: "Liddes", canton: "VS" },
  { postalCode: "1946", locality: "Bourg-St-Pierre", canton: "VS" },
  { postalCode: "1947", locality: "Versegères", canton: "VS" },
  { postalCode: "1948", locality: "Lourtier", canton: "VS" },
  { postalCode: "1950", locality: "Sion", canton: "VS" },
  { postalCode: "1951", locality: "Sion", canton: "VS" },
  { postalCode: "1955", locality: "Chamoson", canton: "VS" },
  { postalCode: "1956", locality: "St-Pierre-de-Clages", canton: "VS" },
  { postalCode: "1957", locality: "Ardon", canton: "VS" },
  { postalCode: "1958", locality: "Uvrier", canton: "VS" },
  { postalCode: "1961", locality: "Vernamiège", canton: "VS" },
  { postalCode: "1962", locality: "Pont-de-la-Morge", canton: "VS" },
  { postalCode: "1963", locality: "Vétroz", canton: "VS" },
  { postalCode: "1964", locality: "Conthey", canton: "VS" },
  { postalCode: "1965", locality: "Savièse", canton: "VS" },
  { postalCode: "1966", locality: "Ayent", canton: "VS" },
  { postalCode: "1967", locality: "Bramois", canton: "VS" },
  { postalCode: "1968", locality: "Mase", canton: "VS" },
  { postalCode: "1969", locality: "Liez", canton: "VS" },
  { postalCode: "1971", locality: "Grimisuat", canton: "VS" },
  { postalCode: "1972", locality: "Anzère", canton: "VS" },
  { postalCode: "1973", locality: "Nax", canton: "VS" },
  { postalCode: "1974", locality: "Arbaz", canton: "VS" },
  { postalCode: "1975", locality: "St-Séverin", canton: "VS" },
  { postalCode: "1976", locality: "Erde", canton: "VS" },
  { postalCode: "1977", locality: "Icogne", canton: "VS" },
  { postalCode: "1978", locality: "Lens", canton: "VS" },
  { postalCode: "1981", locality: "Vex", canton: "VS" },
  { postalCode: "1982", locality: "Euseigne", canton: "VS" },
  { postalCode: "1983", locality: "Evolène", canton: "VS" },
  { postalCode: "1984", locality: "Les Haudères", canton: "VS" },
  { postalCode: "1985", locality: "La Sage", canton: "VS" },
  { postalCode: "1986", locality: "Arolla", canton: "VS" },
  { postalCode: "1987", locality: "Hérémence", canton: "VS" },
  { postalCode: "1988", locality: "Thyon", canton: "VS" },
  { postalCode: "1991", locality: "Salins", canton: "VS" },
  { postalCode: "1992", locality: "Les Agettes", canton: "VS" },
  { postalCode: "1993", locality: "Veysonnaz", canton: "VS" },
  { postalCode: "1994", locality: "Aproz", canton: "VS" },
  { postalCode: "1996", locality: "Basse-Nendaz", canton: "VS" },
  { postalCode: "1997", locality: "Haute-Nendaz", canton: "VS" },
  { postalCode: "3960", locality: "Sierre", canton: "VS" },
  { postalCode: "3961", locality: "Vissoie", canton: "VS" },
  { postalCode: "3961", locality: "St-Luc", canton: "VS" },
  { postalCode: "3961", locality: "Chandolin", canton: "VS" },
  { postalCode: "3961", locality: "Ayer", canton: "VS" },
  { postalCode: "3961", locality: "Grimentz", canton: "VS" },
  { postalCode: "3961", locality: "Zinal", canton: "VS" },
  { postalCode: "3962", locality: "Montana", canton: "VS" },
  { postalCode: "3963", locality: "Crans-Montana", canton: "VS" },
  { postalCode: "3965", locality: "Chippis", canton: "VS" },
  { postalCode: "3966", locality: "Chalais", canton: "VS" },
  { postalCode: "3967", locality: "Vercorin", canton: "VS" },
  { postalCode: "3968", locality: "Veyras", canton: "VS" },
  { postalCode: "3970", locality: "Salquenen", canton: "VS" },
  { postalCode: "3971", locality: "Chermignon", canton: "VS" },
  { postalCode: "3972", locality: "Miège", canton: "VS" },
  { postalCode: "3973", locality: "Venthône", canton: "VS" },
  { postalCode: "3974", locality: "Mollens", canton: "VS" },
  { postalCode: "3975", locality: "Randogne", canton: "VS" },
  { postalCode: "3976", locality: "Noës", canton: "VS" },
  { postalCode: "3977", locality: "Granges", canton: "VS" },
  { postalCode: "3978", locality: "Flanthey", canton: "VS" },
  { postalCode: "3979", locality: "Grône", canton: "VS" },

  // Neuchâtel (NE) - principales localités
  { postalCode: "2000", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2001", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2002", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2003", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2004", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2006", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2007", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2008", locality: "Neuchâtel", canton: "NE" },
  { postalCode: "2012", locality: "Auvernier", canton: "NE" },
  { postalCode: "2013", locality: "Colombier", canton: "NE" },
  { postalCode: "2014", locality: "Bôle", canton: "NE" },
  { postalCode: "2015", locality: "Areuse", canton: "NE" },
  { postalCode: "2016", locality: "Cortaillod", canton: "NE" },
  { postalCode: "2017", locality: "Boudry", canton: "NE" },
  { postalCode: "2018", locality: "Perreux", canton: "NE" },
  { postalCode: "2019", locality: "Rochefort", canton: "NE" },
  { postalCode: "2022", locality: "Bevaix", canton: "NE" },
  { postalCode: "2023", locality: "Gorgier", canton: "NE" },
  { postalCode: "2024", locality: "St-Aubin-Sauges", canton: "NE" },
  { postalCode: "2025", locality: "Chez-le-Bart", canton: "NE" },
  { postalCode: "2027", locality: "Montalchez", canton: "NE" },
  { postalCode: "2028", locality: "Vaumarcus", canton: "NE" },
  { postalCode: "2034", locality: "Peseux", canton: "NE" },
  { postalCode: "2035", locality: "Corcelles", canton: "NE" },
  { postalCode: "2036", locality: "Cormondrèche", canton: "NE" },
  { postalCode: "2037", locality: "Montmollin", canton: "NE" },
  { postalCode: "2042", locality: "Valangin", canton: "NE" },
  { postalCode: "2043", locality: "Boudevilliers", canton: "NE" },
  { postalCode: "2046", locality: "Fontaines", canton: "NE" },
  { postalCode: "2052", locality: "Fontainemelon", canton: "NE" },
  { postalCode: "2053", locality: "Cernier", canton: "NE" },
  { postalCode: "2054", locality: "Chézard-St-Martin", canton: "NE" },
  { postalCode: "2056", locality: "Dombresson", canton: "NE" },
  { postalCode: "2057", locality: "Villiers", canton: "NE" },
  { postalCode: "2058", locality: "Le Pâquier", canton: "NE" },
  { postalCode: "2063", locality: "Vilars", canton: "NE" },
  { postalCode: "2065", locality: "Savagnier", canton: "NE" },
  { postalCode: "2067", locality: "Chaumont", canton: "NE" },
  { postalCode: "2068", locality: "Hauterive", canton: "NE" },
  { postalCode: "2072", locality: "St-Blaise", canton: "NE" },
  { postalCode: "2073", locality: "Enges", canton: "NE" },
  { postalCode: "2074", locality: "Marin-Epagnier", canton: "NE" },
  { postalCode: "2075", locality: "Thielle", canton: "NE" },
  { postalCode: "2088", locality: "Cressier", canton: "NE" },
  { postalCode: "2103", locality: "Noiraigue", canton: "NE" },
  { postalCode: "2105", locality: "Travers", canton: "NE" },
  { postalCode: "2108", locality: "Couvet", canton: "NE" },
  { postalCode: "2112", locality: "Môtiers", canton: "NE" },
  { postalCode: "2113", locality: "Boveresse", canton: "NE" },
  { postalCode: "2114", locality: "Fleurier", canton: "NE" },
  { postalCode: "2115", locality: "Buttes", canton: "NE" },
  { postalCode: "2116", locality: "Mont-de-Buttes", canton: "NE" },
  { postalCode: "2117", locality: "La Côte-aux-Fées", canton: "NE" },
  { postalCode: "2123", locality: "St-Sulpice", canton: "NE" },
  { postalCode: "2124", locality: "Les Sagnettes", canton: "NE" },
  { postalCode: "2126", locality: "Les Verrières", canton: "NE" },
  { postalCode: "2127", locality: "Les Bayards", canton: "NE" },
  { postalCode: "2300", locality: "La Chaux-de-Fonds", canton: "NE" },
  { postalCode: "2301", locality: "La Chaux-de-Fonds", canton: "NE" },
  { postalCode: "2302", locality: "La Chaux-de-Fonds", canton: "NE" },
  { postalCode: "2303", locality: "La Chaux-de-Fonds", canton: "NE" },
  { postalCode: "2304", locality: "La Chaux-de-Fonds", canton: "NE" },
  { postalCode: "2314", locality: "La Sagne", canton: "NE" },
  { postalCode: "2316", locality: "Les Ponts-de-Martel", canton: "NE" },
  { postalCode: "2318", locality: "Brot-Plamboz", canton: "NE" },
  { postalCode: "2322", locality: "Le Crêt-du-Locle", canton: "NE" },
  { postalCode: "2325", locality: "Les Planchettes", canton: "NE" },
  { postalCode: "2400", locality: "Le Locle", canton: "NE" },
  { postalCode: "2405", locality: "La Chaux-du-Milieu", canton: "NE" },
  { postalCode: "2406", locality: "Le Brouillet", canton: "NE" },
  { postalCode: "2414", locality: "Le Cerneux-Péquignot", canton: "NE" },
  { postalCode: "2416", locality: "Les Brenets", canton: "NE" },
  { postalCode: "2523", locality: "Lignières", canton: "NE" },
  { postalCode: "2525", locality: "Le Landeron", canton: "NE" },
  { postalCode: "2532", locality: "Macolin", canton: "BE" },
  { postalCode: "2533", locality: "Evilard", canton: "BE" },

  // Jura (JU)
  { postalCode: "2800", locality: "Delémont", canton: "JU" },
  { postalCode: "2802", locality: "Develier", canton: "JU" },
  { postalCode: "2803", locality: "Bourrignon", canton: "JU" },
  { postalCode: "2805", locality: "Soyhières", canton: "JU" },
  { postalCode: "2806", locality: "Mettembert", canton: "JU" },
  { postalCode: "2807", locality: "Pleigne", canton: "JU" },
  { postalCode: "2812", locality: "Movelier", canton: "JU" },
  { postalCode: "2813", locality: "Ederswiler", canton: "JU" },
  { postalCode: "2814", locality: "Roggenburg", canton: "JU" },
  { postalCode: "2822", locality: "Courroux", canton: "JU" },
  { postalCode: "2823", locality: "Courcelon", canton: "JU" },
  { postalCode: "2824", locality: "Vicques", canton: "JU" },
  { postalCode: "2825", locality: "Courchapoix", canton: "JU" },
  { postalCode: "2826", locality: "Corban", canton: "JU" },
  { postalCode: "2827", locality: "Mervelier", canton: "JU" },
  { postalCode: "2828", locality: "Montsevelier", canton: "JU" },
  { postalCode: "2829", locality: "Vermes", canton: "JU" },
  { postalCode: "2830", locality: "Courrendlin", canton: "JU" },
  { postalCode: "2832", locality: "Rebeuvelier", canton: "JU" },
  { postalCode: "2843", locality: "Châtillon", canton: "JU" },
  { postalCode: "2852", locality: "Courtételle", canton: "JU" },
  { postalCode: "2853", locality: "Courfaivre", canton: "JU" },
  { postalCode: "2854", locality: "Bassecourt", canton: "JU" },
  { postalCode: "2855", locality: "Glovelier", canton: "JU" },
  { postalCode: "2856", locality: "Boécourt", canton: "JU" },
  { postalCode: "2857", locality: "Montavon", canton: "JU" },
  { postalCode: "2863", locality: "Undervelier", canton: "JU" },
  { postalCode: "2864", locality: "Soulce", canton: "JU" },
  { postalCode: "2873", locality: "Saulcy", canton: "JU" },
  { postalCode: "2874", locality: "St-Brais", canton: "JU" },
  { postalCode: "2882", locality: "St-Ursanne", canton: "JU" },
  { postalCode: "2883", locality: "Montmelon", canton: "JU" },
  { postalCode: "2884", locality: "Montenol", canton: "JU" },
  { postalCode: "2885", locality: "Epauvillers", canton: "JU" },
  { postalCode: "2886", locality: "Epiquerez", canton: "JU" },
  { postalCode: "2887", locality: "Soubey", canton: "JU" },
  { postalCode: "2888", locality: "Seleute", canton: "JU" },
  { postalCode: "2889", locality: "Ocourt", canton: "JU" },
  { postalCode: "2900", locality: "Porrentruy", canton: "JU" },
  { postalCode: "2902", locality: "Fontenais", canton: "JU" },
  { postalCode: "2903", locality: "Villars-sur-Fontenais", canton: "JU" },
  { postalCode: "2904", locality: "Bressaucourt", canton: "JU" },
  { postalCode: "2905", locality: "Courtedoux", canton: "JU" },
  { postalCode: "2906", locality: "Chevenez", canton: "JU" },
  { postalCode: "2907", locality: "Rocourt", canton: "JU" },
  { postalCode: "2908", locality: "Grandfontaine", canton: "JU" },
  { postalCode: "2912", locality: "Roche-d'Or", canton: "JU" },
  { postalCode: "2914", locality: "Damvant", canton: "JU" },
  { postalCode: "2915", locality: "Bure", canton: "JU" },
  { postalCode: "2916", locality: "Fahy", canton: "JU" },
  { postalCode: "2922", locality: "Courchavon", canton: "JU" },
  { postalCode: "2923", locality: "Courtemaîche", canton: "JU" },
  { postalCode: "2924", locality: "Montignez", canton: "JU" },
  { postalCode: "2925", locality: "Buix", canton: "JU" },
  { postalCode: "2926", locality: "Boncourt", canton: "JU" },
  { postalCode: "2932", locality: "Coeuve", canton: "JU" },
  { postalCode: "2933", locality: "Damphreux", canton: "JU" },
  { postalCode: "2934", locality: "Beurnevésin", canton: "JU" },
  { postalCode: "2935", locality: "Bonfol", canton: "JU" },
  { postalCode: "2942", locality: "Alle", canton: "JU" },
  { postalCode: "2943", locality: "Vendlincourt", canton: "JU" },
  { postalCode: "2944", locality: "Bonfol", canton: "JU" },
  { postalCode: "2946", locality: "Miécourt", canton: "JU" },
  { postalCode: "2947", locality: "Charmoille", canton: "JU" },
  { postalCode: "2948", locality: "Rossemaison", canton: "JU" },
  { postalCode: "2950", locality: "Courgenay", canton: "JU" },
  { postalCode: "2952", locality: "Cornol", canton: "JU" },
  { postalCode: "2953", locality: "Fregiécourt", canton: "JU" },
  { postalCode: "2954", locality: "Asuel", canton: "JU" },
];
